#!/bin/sh

set -e

#exec 3>&1 # make stdout available as fd 3 so as to not mix-in command output
#exec 1>&2 # redirect all normal output to stderr for logging

PARAMS="$(cat)"
DEBUG="$(echo "$PARAMS" | jq -r '.source.debug//empty')"
URL="$(echo "$PARAMS" | jq -r '.source.url//empty')"
GROUP="$(echo "$PARAMS" | jq -r '.source.group//empty' | sed 's/\./\//g')"
NAME="$(echo "$PARAMS" | jq -r '.source.name//empty')"
VERSION="$(echo "$PARAMS" | jq -r '.source.version//empty')"
CLASSIFIER="$(echo "$PARAMS" | jq -r '.source.classifier//empty')"

[ -z "$DEBUG" ] || echo "DEBUG: $PARAMS" >&2

[ -z "$CLASSIFIER" ] || CLASSIFIER="-$CLASSIFIER"

[ -z "$URL" ] && echo "Maven 'url' not set" >&2 && exit 0
[ -z "$GROUP" ] && echo "Maven 'group' not set" >&2 && exit 0
[ -z "$NAME" ] && echo "Maven 'name' not set" >&2 && exit 0

if [ -z "$VERSION" ]; then # if version is empty then get latest release
	METADATA=$(curl -L "$URL/$GROUP/$NAME/maven-metadata.xml" 2>/dev/null)
	[ -z "$DEBUG" ] || echo "DEBUG METADATA: $METADATA" >&2
	[ -z "$METADATA" ] && exit 3
	LAST_RELEASE="$(echo "$METADATA" | xmllint --xpath '//metadata/versioning/release//text()' -)"
	[ -z "$DEBUG" ] || echo "DEBUG LAST_RELEASE: $LAST_RELEASE" >&2
	curl -L "$URL/$GROUP/$NAME/$LAST_RELEASE/$NAME-$LAST_RELEASE$CLASSIFIER.jar" 2>/dev/null > "$1/$NAME-$LAST_RELEASE$CLASSIFIER.jar" || exit 4
	jq -cn "{version: {ref: \"$LAST_RELEASE\"}, metadata: []}"
else # get information on that specific release
	LAST_UPDATE="$(curl -LI "$URL/$GROUP/$NAME/$VERSION/$NAME-$VERSION$CLASSIFIER.jar" 2>/dev/null | grep -i 'Last-Modified:' | head -n 1 | sed 's/[lL][aA][sS][tT]-[mM][oO][dD][iI][fF][iI][eE][dD]: *//' | sed 's/\r//')"
	[ -z "$DEBUG" ] || echo "DEBUG LAST_UPDATE: $LAST_UPDATE" >&2
	if [ -z "$LAST_UPDATE" ]; then
		echo "No 'Last-Modified' header at: $URL/$GROUP/$NAME/$NAME-$VERSION.jar" >&2
		exit 1
	else
		curl -L "$URL/$GROUP/$NAME/$VERSION/$NAME-$VERSION.jar" 2>/dev/null > "$1/$NAME-$VERSION$CLASSIFIER.jar" || exit 2
		jq -cn "{version: {ref: \"$LAST_UPDATE\"}, metadata: []}"
	fi
fi

