#!/bin/sh

set -e

#exec 3>&1 # make stdout available as fd 3 so as to not mix-in command output
#exec 1>&2 # redirect all normal output to stderr for logging

PARAMS="$(cat)"
DEBUG="$(echo "$PARAMS" | jq -r '.source.debug//empty')"
URL="$(echo "$PARAMS" | jq -r '.source.url//empty')"
PUT_URL="$(echo "$PARAMS" | jq -r ".source[\"put-url\"]//empty")"
[ -z "$PUT_URL" ] || PUT_URL="$URL"
DIR="$(echo "$PARAMS" | jq -r ".source.dir//empty")"
CMD="$(echo "$PARAMS" | jq -r ".source.cmd // \"gradle uploadArchives\"")"

VERSION_CMD="$(echo "$PARAMS" | jq -r ".params[\"version-cmd\"]//empty")"
METADATA_CMD="$(echo "$PARAMS" | jq -r ".params[\"metadata-cmd\"]//empty")"

[ -z "$URL" ] && echo "Maven 'url' not set" >&2 && exit 0

MAVEN_ENV="$(echo "$PARAMS" | jq -r '.source.env | to_entries | map("export "+(.key|gsub("[^a-zA-Z0-9_]+";"_"))+"="+(.value|tostring|@sh)) | join("\n") // empty')"

[ -z "$DEBUG" ] || echo "DEBUG: $PARAMS" >&2

sh -c "
  cd \"$1/$DIR\"
  $MAVEN_ENV
  $CMD
" >&2

#VERSIONS=$(echo "$PARAMS" | /opt/resource/check)

VERSION=$(sh -c "cd '$1'; $VERSION_CMD")
METADATA='[]'
[ -z "$METADATA_CMD" ] || METADATA=$(sh -c "$METADATA_CMD")
[ -z "$DEBUG" ] || echo "DEBUG VERSION METADATA: $VERSION : $METADATA" >&2
jq -cn "{version: {ref: \"$VERSION\"}, metadata: $METADATA}"


